sudo: false
language: node_js
node_js:
    - "14"
cache:
    directories:
        - node_modules
script:
    - npm run lint
    - npm run build
    - npm run test
after_script:
    # 部署到 https://miaomiaofanny.github.io/plane-war/
    - set -e
    - cd ./dist
    - git init
    - git config user.name "${U_NAME}"
    - git config user.email "${U_EMAIL}"
    - git add .
    - git commit -m "deploy by travis CI"
    - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
